package com.daddyizz.cyberpulse.core.recommendation

import com.daddyizz.cyberpulse.core.model.Track
import java.util.UUID

/**
 * Structured model describing the listener's intent generated by AI or local rules.
 *
 * CRITICAL INVARIANT:
 * AI NEVER returns fabricated tracks or audio URLs. It solely produces structured intent
 * parameters (moods, genres, energy, eras, artists), which CyberPulse's Query Planner
 * and Candidate Ranker resolve against verified on-device, radio, and permitted catalog sources.
 */
data class PlaylistIntent(
    val title: String,
    val description: String?,
    val genres: List<String> = emptyList(),
    val moods: List<String> = emptyList(),
    val eras: List<String> = emptyList(),
    val artists: List<String> = emptyList(),
    val excludedArtists: List<String> = emptyList(),
    val energy: Int? = 50, // 1 to 100
    val tempoPreference: String? = null, // "slow", "moderate", "fast", "uptempo"
    val languagePreferences: List<String> = emptyList(),
    val targetTrackCount: Int = 15,
    val activity: String? = null
)

/**
 * Core operating modes for Cyber DJ.
 */
enum class CyberDjMode(
    val displayName: String,
    val description: String,
    val defaultEnergy: Int,
    val defaultDiscovery: Float, // 0.0 (familiar) to 1.0 (novel)
    val isProExclusive: Boolean = false
) {
    DRIVE(
        displayName = "Drive",
        description = "Steady, focused beats for open highways and urban streets",
        defaultEnergy = 65,
        defaultDiscovery = 0.3f,
        isProExclusive = false
    ),
    CHILL(
        displayName = "Chill",
        description = "Mellow frequencies, lo-fi textures, and ambient soundscapes",
        defaultEnergy = 30,
        defaultDiscovery = 0.4f,
        isProExclusive = false
    ),
    WORKOUT(
        displayName = "Workout",
        description = "High-octane BPM, synth pulses, and adrenaline surges",
        defaultEnergy = 90,
        defaultDiscovery = 0.5f,
        isProExclusive = false
    ),
    FOCUS(
        displayName = "Focus",
        description = "Deep electronic flow, minimal vocals, and steady cognitive momentum",
        defaultEnergy = 45,
        defaultDiscovery = 0.2f,
        isProExclusive = false
    ),
    PARTY(
        displayName = "Party",
        description = "Banger electronic anthems, dancefloor movers, and peak-hour energy",
        defaultEnergy = 95,
        defaultDiscovery = 0.6f,
        isProExclusive = true
    ),
    SLEEP(
        displayName = "Sleep",
        description = "Sub-bass drones, generative binaural chill, and relaxing drift",
        defaultEnergy = 15,
        defaultDiscovery = 0.1f,
        isProExclusive = true
    ),
    DISCOVER(
        displayName = "Discover",
        description = "High novelty radar unearthing new artists and unplayed pulses",
        defaultEnergy = 60,
        defaultDiscovery = 0.9f,
        isProExclusive = true
    ),
    THROWBACK(
        displayName = "Throwback",
        description = "Vintage synthwave, retro 80s/90s nostalgia, and golden classics",
        defaultEnergy = 70,
        defaultDiscovery = 0.4f,
        isProExclusive = true
    )
}

/**
 * Plan describing the trajectory of an active continuous Cyber DJ session.
 */
data class DjSessionPlan(
    val id: String = UUID.randomUUID().toString(),
    val mode: CyberDjMode,
    val targetEnergy: Int = mode.defaultEnergy,
    val discoveryRatio: Float = mode.defaultDiscovery,
    val primaryGenres: List<String> = emptyList(),
    val targetMoods: List<String> = emptyList(),
    val seedArtists: List<String> = emptyList(),
    val seedKeywords: List<String> = emptyList(),
    val tempoPreference: String? = null
)

/**
 * Playable source mode for playlist generation.
 */
enum class PlaylistResolutionMode {
    /**
     * Strictly Media3-direct playable tracks (Local Audio, Cyber Radio, Verified Test/Demo audio).
     * Mandatory for Android Auto, background playback, and uninterrupted listening.
     * Zero YouTube embedded or external player items allowed.
     */
    PLAYABLE_NOW,

    /**
     * Discovery mix (Phone only). May include YouTube discovery metadata alongside playable streams.
     * YouTube embedded items remain visual and are never pushed to Media3 car queue.
     */
    DISCOVERY
}

/**
 * Breakdown of sources comprising a generated playlist.
 */
data class SourceComposition(
    val localCount: Int = 0,
    val radioCount: Int = 0,
    val demoPlayableCount: Int = 0,
    val discoveryCount: Int = 0
) {
    val totalCount: Int get() = localCount + radioCount + demoPlayableCount + discoveryCount
}

/**
 * Fully resolved playlist ready for preview, playback, or saving.
 */
data class ResolvedPlaylist(
    val id: String = "ai_pl_${System.currentTimeMillis()}",
    val title: String,
    val description: String?,
    val intent: PlaylistIntent,
    val tracks: List<Track>,
    val resolutionMode: PlaylistResolutionMode,
    val sourceComposition: SourceComposition,
    val generatedAtEpoch: Long = System.currentTimeMillis()
) {
    val estimatedDurationSeconds: Long
        get() = tracks.sumOf { it.durationSeconds }

    val formattedDuration: String
        get() {
            val totalSec = estimatedDurationSeconds
            if (totalSec <= 0) return "${tracks.size} tracks"
            val hrs = totalSec / 3600
            val mins = (totalSec % 3600) / 60
            return if (hrs > 0) "${hrs} hr ${mins} min" else "${mins} min"
        }
}

/**
 * Structured AI errors with friendly user-facing explanations.
 */
sealed class AiGenerationError(val message: String, val canFallbackLocally: Boolean = true) {
    data object NoNetwork : AiGenerationError("No internet connection available. Switched to smart offline mix.", canFallbackLocally = true)
    data object RateLimited : AiGenerationError("AI generation rate limit reached. Using local smart recommendation engine.", canFallbackLocally = true)
    data object ProviderUnavailable : AiGenerationError("AI discovery service is temporarily unavailable. Generating local smart mix.", canFallbackLocally = true)
    data object MalformedResponse : AiGenerationError("AI response format was invalid. Generating local smart mix instead.", canFallbackLocally = true)
    data object NoPlayableResults : AiGenerationError("No available playable tracks matched this exact prompt. Try refining your request.", canFallbackLocally = false)
    data object SafetyRejection : AiGenerationError("Prompt could not be processed due to safety guidelines.", canFallbackLocally = false)
    data object QuotaExceeded : AiGenerationError("Daily free AI generations limit reached. Upgrade to CyberPulse Pro for expanded access.", canFallbackLocally = true)
    data class Unknown(val errorMsg: String) : AiGenerationError(errorMsg, canFallbackLocally = true)
}
